app:
  environment: 'uat'

replicaCount: 2

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 15
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

resources:
  limits:
    cpu: 150m
    memory: 350Mi
  requests:
    cpu: 100m
    memory: 300Mi

istio:
  hosts: ["expense-flow-api.uat.claitdev.com"]

serviceAccount:
  azureWorkloadIdentityClientId: '<uat-expense-flow-api-uami-client-id>'
