app: # Application version
  environment: 'qa' # Environment (dev/qa/stage/prod)

replicaCount: 1

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

resources:
  limits:
    cpu: 150m
    memory: 350Mi
  requests:
    cpu: 100m
    memory: 300Mi

istio:
  hosts: ["<app-hostname>.qa.claitdev.com"]

serviceAccount:
  azureWorkloadIdentityClientId: '<azure-workload-identity-client-id>' #qa-<env>-<app>-uami-001
