services:
  frontend:
    build:
      context: .
      target: base
      args:
        NPM_TOKEN: "${NPM_TOKEN:-}"
    ports:
      - "3000:3000"
      - "6006:6006"
    volumes:
      - ./src:/opt/cla/src
      - ./public:/opt/cla/public
      - ./vite.config.ts:/opt/cla/vite.config.ts
      - ./eslint.config.js:/opt/cla/eslint.config.js
      - ./package.json:/opt/cla/package.json
      - ./tsconfig.json:/opt/cla/tsconfig.json
      - ./tsconfig.app.json:/opt/cla/tsconfig.app.json
      - ./tsconfig.node.json:/opt/cla/tsconfig.node.json
      - ./test:/opt/cla/test
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8080
