app:
  name: web-expense-flow
  version: 1.0.0

image:
  registry: cladevops.azurecr.io
  repository: helm/web-expense-flow
  tag: latest

container:
  port: 3000
  readinessProbe:
    httpGet:
      path: /
      port: 3000
  livenessProbe:
    httpGet:
      path: /
      port: 3000
    initialDelaySeconds: 30
    timeoutSeconds: 10
    failureThreshold: 5

service:
  type: ClusterIP
  port: 80
  targetPort: 3000
  name: web-expense-flow

ingress:
  enabled: false

istio:
  enabled: true
  hosts: ["*"]
  gateways: ["web-expense-flow-ingress-gateway"]
  pathPrefix: "/"
  timeout: 30s
  gateway:
    enabled: false
  authorizationPolicy:
    enabled: true
    name: allow-cross-ns
    namespace: expense-flow
    allowedServiceAccounts:
      - namespace: istio-ingress
        name: istio-ingress

serviceAccount:
  create: true
  annotations: {}
  name: "web-expense-flow"

configMap:
  enabled: false

secret:
  enabled: false

podDisruptionBudget:
  enabled: false

networkPolicy:
  enabled: false

healthcheck:
  enabled: false

monitoring:
  serviceMonitor:
    enabled: false

volumeMounts: []
volumes: []

nodeSelector: {}
tolerations: []
affinity: {}
