parameters:
  - name: rollback
    displayName: Rollback Application?
    type: boolean
    default: false

trigger:
- main

resources:
  repositories:
  - repository: pipelines-devops
    type: git
    name: "pipelines-devops"
    ref: main
  - repository: system-test-templateweb
    type: git
    name: 'system-test-templateweb'
    ref: main

pool: $(poolName)

variables:
  # variable groups
  - group: common
  - group: common-dynatrace
  - group: common-qa
  - group: common-servicenow
  - group: common-templateweb
  - group: system-test-templateweb
  - group: veracode
  - group: web-api-templateweb-base
  - group: web-templateweb-qa-accounts
  - group: web-api-templateweb-base-quality

  - template: templates/variables/standard.yml@pipelines-devops

  - name: isRollback
    value: ${{parameters.rollback}}

stages:
# ==============================================================================
# development
# ==============================================================================
  - stage: development
    displayName: Development
    condition: eq(variables.isRollback, false)
    jobs:
      - job: processVersion
        displayName: Process Version
        steps:
          - template: templates/steps/checkout.yml@pipelines-devops
          - template: templates/debug/buildVariables.yml@pipelines-devops
          - template: templates/debug/templateVariables.yml@pipelines-devops
            parameters:
              imageName: $(imageName)
              isMain: $(isMain)
          - template: templates/steps/setVersion.yml@pipelines-devops
          - ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
            - template: templates/steps/servicenow-configRequest.yml@pipelines-devops
              parameters:
                containerRegistryService: $(containerRegistryService)
                containerRegistryHost:    $(containerRegistryHost)
                projectName:              $(System.TeamProject)
                commitHash:               $(Build.SourceVersion)
                prNumber:                 $(System.PullRequest.PullRequestId)
                repository:               $(Build.Repository.Name)
                requestorEmail:           $(Build.RequestedForEmail)
                snClientId:               $(snClientIdProd)
                snClientSecret:           $(snClientSecretProd)
                snPassword:               $(snPasswordProd)
                snUsername:               $(snUsernameProd)
                systemToken:              $(System.AccessToken)

      - job: testDevelopment
        displayName: Execute Development Tests
        dependsOn: processVersion
        variables:
          imageTag: $[dependencies.processVersion.outputs['setVersion.imageTagVersion']]
        steps:
          - template: templates/steps/checkout.yml@pipelines-devops
          - template: templates/jobs/testDevelopment.yml@pipelines-devops
            parameters:
              containerRegistryService: $(containerRegistryService)
              imageName:                $(imageName)
              imageTag:                 $(imageTag)
              azTenant:                 $(azTenant)
              codeCovClientId:          $(codeCovClientId)
              codeCovClientSecret:      $(codeCovClientSecret)
              codeCovDriveId:           $(codeCovDriveId)
              codeCovDriveItemId:       $(codeCovDriveItemId)
              codeCovTableName:         $(codeCovTableName)
              codeCoverageCeiling:      $(codeCoverageCeiling)
              codeCoverageFloor:        $(codeCoverageFloor)

      - job: build
        displayName: Build and Push Solution
        dependsOn:
          - processVersion
          - testDevelopment
        condition: and(succeeded(), eq(variables.isMain, true))
        variables:
          imageTag: $[dependencies.processVersion.outputs['setVersion.imageTagVersion']]
        steps:
          - template: templates/steps/checkout.yml@pipelines-devops
          - task: Docker@2
            displayName: Login to ACR
            inputs:
              command: login
              containerRegistry: $(containerRegistryService)
          - task: Docker@2
            displayName: Build Image
            inputs:
              command: build
              repository: $(imageName)
              arguments: >
                --build-arg DT_API_TOKEN=$(dtApiToken)
                --build-arg DT_ENDPOINT=$(dtEndpoint)
              tags: |
                latest
                $(imageTag)
          - task: Docker@2
            displayName: Push Image
            inputs:
              command: push
              repository: $(imageName)
              tags: |
                latest
                $(imageTag)
              containerRegistry: $(containerRegistryService)

      - deployment: deployDEV
        displayName: Deploy to DEV
        dependsOn:
          - processVersion
          - build
        condition: and(succeeded(), eq(variables.isMain, true))
        variables:
          imageTag: $[dependencies.processVersion.outputs['setVersion.imageTagVersion']]
          targetEnv: "DEV"
        environment: templateweb-dev
        strategy:
          runOnce:
            deploy:
              steps:
                - template: templates/jobs/azureAppService-deploy.yml@pipelines-devops
                  parameters:
                    targetEnv:                $(targetEnv)
                    containerRegistryHost:    $(containerRegistryHost)
                    imageName:                $(imageName)
                    imageTag:                 $(imageTag)
                    serviceConnection:        $(devService)
                    webApp:                   $(devWebApp)
                    webAppFailover:           $(devWebAppFailover)
                    programName:              $(adminSolutionName)
                    productOwner:             $(adminProductOwner)
                    changeAuthor:             $(Build.RequestedForEmail)
                    techStack:                "NodeJS"

# ==============================================================================
# security
# ==============================================================================
  - template: templates/stages/security.yml@pipelines-devops
    parameters:
      pipelinevariables:
        _1: common
        _2: veracode
        _3: web-api-templateweb-base-security
        _4: web-api-templateweb-base-control-flow
      containerRegistryServiceConnection: $(containerRegistryService)
      analysisServiceConnection: $(analysisService)

# ==============================================================================
# quality assurance
# ==============================================================================
  - stage: qualityAssurance
    displayName: Quality Assurance
    dependsOn: development
    condition: and(succeeded(), eq(variables.isMain, true), eq(variables.isRollback, false))
    variables:
      imageTag: $[stageDependencies.development.processVersion.outputs['setVersion.imageTagVersion']]
      targetEnv: "QA"
    jobs:
      - deployment: deployQA
        displayName: Deploy to QA
        environment: templateweb-qa
        strategy:
          runOnce:
            deploy:
              steps:
                - template: templates/jobs/azureAppService-deploy.yml@pipelines-devops
                  parameters:
                    targetEnv:                $(targetEnv)
                    containerRegistryHost:    $(containerRegistryHost)
                    imageName:                $(imageName)
                    imageTag:                 $(imageTag)
                    serviceConnection:        $(qaService)
                    webApp:                   $(qaWebApp)
                    webAppFailover:           $(qaWebAppFailover)
                    programName:              $(adminSolutionName)
                    productOwner:             $(adminProductOwner)
                    changeAuthor:             $(Build.RequestedForEmail)
                    techStack:                "NodeJS"

      - job: testSystem
        displayName: Execute System Tests
        dependsOn: deployQA
        steps:
          - template: templates/steps/checkout.yml@pipelines-devops
            parameters:
              repository: 'system-test-templateweb'
          - template: templates/jobs/testSystem.yml@pipelines-devops
            parameters:
              containerRegistryService: $(containerRegistryService)
              moduleName:               $(systemTestImageName)
              healthCheckUrl:           'http://localhost:4444'
              runScreenshotsPublishing: "True"
              runCommand:               $(systemTestRunCommand)
              envVariables:
                SITE_URL:                    $(qaWebAppUrl)
                SELENIUM_HUB_URL:            'http://hub:4444'
                SELENIUM_HUB_VERSION:        $(seleniumHubVersion)
                AUTH_ADMINISTRATOR_USERNAME: $(Administrator-UserName)
                AUTH_ADMINISTRATOR_PASSWORD: $(Administrator-Password)
                AUTH_EMPLOYEE_USERNAME:      $(Employee-UserName)
                AUTH_EMPLOYEE_PASSWORD:      $(Employee-Password)
                AUTH_CLIENT_USERNAME:        $(Client-UserName)
                AUTH_CLIENT_PASSWORD:        $(Client-Password)
                DEVICE_CODE_CLIENT_ID:       $(qaDeviceCodeAppID)
                DEVICE_CODE_AUTHORITY:       $(qaDeviceCodeAuthority)
                CAP_W3C_BROWSER_NAME:        $(browserName)
                CAP_W3C_BROWSER_VERSION:     $(browserVersion)
                CAP_W3C_PLATFORM_NAME:       $(platformName)
                CAP_SL_BUILD:                $(imageName):$(imageTag)-$(Build.Reason)-$(Build.BuildNumber)
                CONTAINER_REGISTRY_HOST:     $(containerRegistryHost)
                SYSTEM_TEST_IMAGE:           $(systemTestImageName)
                WEB_BASE_URL:                $(web_base_url)
                TEMPLATE_WEB_PREFIX:         $(web_base_scope_prefix)

# ==============================================================================
# user acceptance
# ==============================================================================
  - stage: userAcceptance
    displayName: User Acceptance
    dependsOn:
      - development
      - qualityAssurance
      - security
    condition: and(succeeded(), eq(variables.isMain, true), eq(variables.isRollback, false))
    variables:
      imageTag: $[stageDependencies.development.processVersion.outputs['setVersion.imageTagVersion']]
      targetEnv: "UAT"
    jobs:
      - deployment: deployUAT
        displayName: Deploy to UAT
        environment: templateweb-uat
        strategy:
          runOnce:
            deploy:
              steps:
                - template: templates/jobs/azureAppService-deploy.yml@pipelines-devops
                  parameters:
                    targetEnv:                $(targetEnv)
                    containerRegistryHost:    $(containerRegistryHost)
                    imageName:                $(imageName)
                    imageTag:                 $(imageTag)
                    serviceConnection:        $(uatService)
                    webApp:                   $(uatWebApp)
                    webAppFailover:           $(uatWebAppFailover)
                    programName:              $(adminSolutionName)
                    productOwner:             $(adminProductOwner)
                    changeAuthor:             $(Build.RequestedForEmail)
                    techStack:                "NodeJS"

      - job: testUAT
        displayName: Execute Acceptance Tests
        dependsOn: deployUAT
        pool: server
        timeoutInMinutes: 4320
        steps:
          - template: templates/steps/manualConfirmation.yml@pipelines-devops
            parameters:
              taskDisplayName:            'Execute Acceptance Tests'
              notificationMailbox:        $(uatNotificationMailbox)
              notificationInstructions:   'Please execute acceptance tests and report results.'
              timeoutAction:              'reject'

# ==============================================================================
# production
# ==============================================================================
  - stage: production
    displayName: Production
    dependsOn:
      - development
      - qualityAssurance
      - security
    condition: and(
        in(dependencies.development.result, 'Succeeded', 'Skipped'),
        in(dependencies.qualityAssurance.result, 'Succeeded', 'Skipped'),
        in(dependencies.security.result, 'Succeeded', 'Skipped'),
        eq(variables.isMain, true)
      )
    variables:
      imageTag: $[stageDependencies.development.processVersion.outputs['setVersion.imageTagVersion']]
      semanticVersion: $[stageDependencies.development.processVersion.outputs['setVersion.semanticVersion']]
      targetEnv: "PROD"
    jobs:
      - deployment: deployProduction
        displayName: Deploy to Production
        condition: eq(variables.isRollback, false)
        environment: templateweb-prod
        strategy:
          runOnce:
            deploy:
              steps:
                - template: templates/jobs/azureAppService-prodDeploy.yml@pipelines-devops
                  parameters:
                    targetEnv:                $(targetEnv)
                    containerRegistryHost:    $(containerRegistryHost)
                    imageName:                $(imageName)
                    imageTag:                 $(imageTag)
                    serviceConnection:        $(prodService)
                    resourceGroup:            $(prodResourceGroup)
                    webApp:                   $(prodWebApp)
                    stagingSlot:              $(prodStagingSlot)
                    webAppFailover:           $(prodWebAppFailover)
                    programName:              $(adminSolutionName)
                    productOwner:             $(adminProductOwner)
                    changeAuthor:             $(Build.RequestedForEmail)
                    techStack:                "NodeJS"

      - job: tagging
        displayName: Tag Commit
        dependsOn:
          - deployProduction
        condition: and(succeeded(), eq(variables.isMain, true), eq(variables.isRollback, false))
        steps:
          - template: templates/jobs/tagging.yml@pipelines-devops
            parameters:
              imageTag:         $(imageTag)
              semanticVersion:  $(semanticVersion)
              project:          $(System.TeamProject)
              repository:       $(Build.Repository.Name)
              systemToken:      $(System.AccessToken)
              name:             $(Build.RequestedFor)
              email:            $(Build.RequestedForEmail)

      - job: submitChangeRequest
        displayName: Submit Change Request
        condition: eq(variables.isRollback, false)
        dependsOn:
          - deployProduction
        steps:
          - template: templates/jobs/servicenow-changeRequest.yml@pipelines-devops
            parameters:
              commitId:                 $(Build.SourceVersion)
              containerRegistryService: $(containerRegistryService)
              containerRegistryHost:    $(containerRegistryHost)
              adminDevGroup:            $(adminDevGroup)
              adminLeadDev:             $(adminLeadDev)
              adminProductOwner:        $(adminProductOwner)
              programName:              $(adminProgramName)
              projectName:              $(System.TeamProject)
              repoId:                   $(Build.DefinitionName)
              snClientId:               $(snClientIdProd)
              snClientSecret:           $(snClientSecretProd)
              snPassword:               $(snPasswordProd)
              snUsername:               $(snUsernameProd)
              adminSolutionName:        $(adminSolutionName)
              systemToken:              $(System.AccessToken)

      - job: productionRollback
        displayName: Production Rollback
        condition: eq(variables.isRollback, true)
        steps:
          - template: templates/jobs/azureAppService-rollback.yml@pipelines-devops
            parameters:
              email:              $(Build.RequestedForEmail)
              name:               $(Build.RequestedFor)
              project:            $(System.TeamProject)
              repository:         $(Build.Repository.Name)
              resourceGroup:      $(prodResourceGroup)
              serviceConnection:  $(prodService)
              stagingSlot:        $(prodStagingSlot)
              systemToken:        $(System.AccessToken)
              webApp:             $(prodWebApp)
